config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: redirect('/customers')

  resources :customers
  resources :payment_methods, only: [:index, :show, :new, :create, :destroy]
  resources :payments, only: [:index, :show, :new, :create, :destroy] do
    member do
      post :pay
      post :confirm
    end
  end
  resources :payment_transactions, only: [:index, :show]
end

app/models/customer.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: customers
#
#  id                  :integer          not null, primary key
#  full_name           :string           not null
#  email               :string           not null
#  revolut_customer_id :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#
# Indexes
#
#  index_customers_on_email  (email) UNIQUE
#
class Customer < ApplicationRecord
  has_many :payment_method_setups, class_name: 'PaymentMethodSetup', dependent: :restrict_with_exception
  has_many :payment_methods, class_name: 'PaymentMethod', dependent: :restrict_with_exception
  has_many :payments, class_name: 'Payment', dependent: :restrict_with_exception

  validates :full_name, presence: true
  validates :email, presence: true
  validates :email, uniqueness: true, allow_blank: true
  validate :readonly_revolut_customer_id

  def readonly_revolut_customer_id
    errors.add(:revolut_customer_id, 'is readonly') if revolut_customer_id_changed? && revolut_customer_id_was.present?
  end

  after_create :create_revolut_customer
  after_update :sync_revolut_customer
  after_destroy :remove_revolut_customer

  def display_name
    "#{id} | #{full_name}"
  end

  def revolut_customer
    RevolutMerchant::Client.customer(revolut_customer_id)
  rescue RevolutMerchant::Errors::ApiError => e
    {
      error_class: e.class.name,
      error_message: e.message,
      response_status: e.status,
      response_body: e.response_body
    }
  end

  private

  def create_revolut_customer
    revolut_customer = RevolutMerchant::Client.customer_create(email:, full_name:)
    update_columns(revolut_customer_id: revolut_customer[:id])
  end

  def sync_revolut_customer
    return if !saved_change_to_email? && !saved_change_to_full_name?

    RevolutMerchant::Client.customer_update(revolut_customer_id, email:, full_name:)
  end

  def remove_revolut_customer
    payment_method_setups.find_each(&:remove!)
    RevolutMerchant::Client.customer_delete(revolut_customer_id)
  end
end

app/controllers/customers_controller.rb
# frozen_string_literal: true

class CustomersController < ApplicationController
  before_action :build_customer, only: [:new, :create]
  before_action :find_customer, only: [:show, :edit, :update, :destroy]

  def index
    @customers = Customer.all.to_a
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    permitted_params = params.require(:customer).permit(:email, :full_name)
    @customer.assign_attributes(permitted_params)
    if @customer.save
      flash[:notice] = 'Customer created'
      redirect_to url_for(action: :index)
    else
      render :new, status: 422
    end
  end

  def update
    permitted_params = params.require(:customer).permit(:email, :full_name)
    @customer.assign_attributes(permitted_params)
    if @customer.save
      flash[:notice] = 'Customer updated'
      redirect_to url_for(action: :index)
    else
      render :edit, status: 422
    end
  end

  def destroy
    if @customer.destroy
      flash[:notice] = 'Customer updated'
      redirect_to url_for(action: :index)
    else
      flash[:alert] = "Can't remove customer: #{@customer.errors.full_messages.to_sentence}"
      redirect_back fallback_location: url_for(action: :index)
    end
  end

  private

  def build_customer
    @customer = Customer.new
  end

  def find_customer
    @customer = Customer.find params[:id]
  end

  def current_menu
    :customers
  end
end

app/views/customers/_customer.html.erb
<div class="card relative w-min h-fit p-2">
  <div class="p-2 font-semibold">Customer details</div>
  <table class="text-sm text-left text-gray-500">
    <tbody>
    <tr class="bg-white border-b">
      <th scope="col" class="text-xs text-gray-700 uppercase px-6 py-3 border-r">ID</th>
      <td class="px-6 py-4">
        <% if controller_name == 'customers' %>
          <%= customer.id %>
        <% else %>
          <%= link_to customer.id, customer_path(customer.id), class: 'link-primary' %>
        <% end %>
      </td>
    </tr>
    <tr class="bg-white border-b">
      <th scope="col" class="text-xs text-gray-700 uppercase px-6 py-3 border-r">Full&nbsp;Name</th>
      <td class="px-6 py-4"><%= customer.full_name %></td>
    </tr>
    <tr class="bg-white border-b">
      <th scope="col" class="text-xs text-gray-700 uppercase px-6 py-3 border-r">Email</th>
      <td class="px-6 py-4"><%= customer.email %></td>
    </tr>
    <tr class="bg-white border-b">
      <th scope="col" class="text-xs text-gray-700 uppercase px-6 py-3 border-r">Created&nbsp;At</th>
      <td class="px-6 py-4 whitespace-nowrap"><%= customer.created_at %></td>
    </tr>
    <tr class="bg-white border-b">
      <th scope="col" class="text-xs text-gray-700 uppercase px-6 py-3 border-r">Updated&nbsp;At</th>
      <td class="px-6 py-4 whitespace-nowrap"><%= customer.updated_at %></td>
    </tr>
    <tr class="bg-white border-b">
      <th scope="col" class="text-xs text-gray-700 uppercase px-6 py-3 border-r">Revolut&nbsp;ID</th>
      <td class="px-6 py-4 whitespace-nowrap"><%= customer.revolut_customer_id %></td>
    </tr>
    <tr class="bg-white border-b">
      <th scope="col" class="text-xs text-gray-700 uppercase px-6 py-3 border-r">Payment&nbsp;Methods</th>
      <td class="px-6 py-4 whitespace-nowrap">
        <%= link_to customer.payment_methods.count, payment_methods_path(q: { customer_id: customer.id }) %>
      </td>
    </tr>
    <tr class="bg-white">
      <th scope="col" class="text-xs text-gray-700 uppercase px-6 py-3 border-r">Payment</th>
      <td class="px-6 py-4 whitespace-nowrap">
        <%= link_to customer.payments.count, payments_path(q: { customer_id: customer.id }) %>
      </td>
    </tr>
    </tbody>
  </table>
</div>

app/views/customers/_form.html.erb
<%= form_for @customer do |f| %>
  <div class="card p-4 flex flex-col gap-y-6 w-fit">
    <%= semantic_errors(f) %>

    <div>
      <%= f.label :full_name, class: 'block' %>
      <%= f.text_field :full_name, class: 'form-input' %>
      <%= form_error(f, :full_name) %>
    </div>

    <div>
      <%= f.label :email, class: 'block' %>
      <%= f.text_field :email, class: 'form-input' %>
      <%= form_error(f, :full_name) %>
    </div>

    <%= f.submit 'Submit', class: 'btn-primary' %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<div class="pb-4">
  <%= link_to '<- Back', customer_path(@customer.id), class: 'link-primary' %>
</div>

<div class="flex justify-between pb-2">
  <div class="page-heading">Edit Customer <%= @customer.id %></div>
</div>

<%= render 'form' %>

app/views/customers/index.html.erb
<div class="flex justify-between">
  <div class="page-heading">Customers</div>

  <div class="flex items-center">
    <%= link_to 'New Customer', new_customer_path, class: 'btn-primary' %>
  </div>
</div>

<% if @customers.any? %>
  <div class="card relative overflow-x-auto">
    <table class="w-full text-sm text-left text-gray-600">
      <thead class="text-xs text-gray-700 font-semibold bg-gray-200">
      <tr>
        <th scope="col" class="px-6 py-3 w-0">ID</th>
        <th scope="col" class="px-6 py-3 w-0">
          <span class="sr-only">Actions</span>
        </th>
        <th scope="col" class="px-6 py-3">Full Name</th>
        <th scope="col" class="px-6 py-3">Email</th>
        <th scope="col" class="px-6 py-3">Revolut ID</th>
      </tr>
      </thead>
      <tbody>
      <% @customers.each do |customer| %>
        <tr class="bg-white odd:bg-gray-50 border-b hover:bg-gray-100">
          <td class="px-6 py-4"><%= customer.id %></td>
          <td class="px-6 py-4">
            <div class="flex flex-row gap-x-2 whitespace-nowrap">
              <%= link_to 'Show',
                          customer_path(customer.id),
                          class: 'link-primary' %>
              <%= link_to 'Edit',
                          edit_customer_path(customer.id),
                          class: 'link-primary' %>
              <%= link_to 'Payment Methods',
                          payment_methods_path(q: { customer_id: customer.id }),
                          class: 'link-primary' %>
              <%= link_to 'Payments',
                          payments_path(q: { customer_id: customer.id }),
                          class: 'link-primary' %>
            </div>
          </td>
          <td class="px-6 py-4"><%= customer.full_name %></td>
          <td class="px-6 py-4"><%= customer.email %></td>
          <td class="px-6 py-4"><%= customer.revolut_customer_id %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <div class="p-5">nothing</div>
<% end %>

app/views/customers/new.html.erb
<div class="pb-4">
  <%= link_to '<- Back', customers_path, class: 'link-primary' %>
</div>

<div class="flex justify-between pb-2">
  <div class="page-heading">New Customer</div>
</div>

<%= render 'form' %>

app/views/customers/show.html.erb
<div class="pb-4">
  <%= link_to '<- Back', customers_path, class: 'link-primary' %>
</div>

<div class="flex justify-between pb-2">
  <div class="page-heading">Customer №<%= @customer.id %></div>

  <div class="flex items-center gap-x-2">
    <%= link_to 'Edit',
                edit_customer_path(@customer.id),
                class: 'btn-primary' %>
    <%= button_to "Remove",
                  customer_path(@customer.id),
                  class: 'btn-danger',
                  method: :delete,
                  form: {
                    data: { turbo_confirm: "Are you sure?" }
                  } %>
    <%= link_to 'New Payment Method',
                new_payment_method_path(customer_id: @customer.id),
                class: 'btn-primary' %>
    <%= link_to 'New Payment',
                new_payment_path(customer_id: @customer.id),
                class: 'btn-primary' %>
  </div>
</div>

<div class="flex flex-row gap-x-4">
  <%= render @customer %>

  <div class="card relative w-min p-4 overflow-x-auto">
    <div class="mb-4 font-semibold">Revolut Customer</div>
    <pre><%= JSON.pretty_generate @customer.revolut_customer %></pre>
  </div>
</div>