config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: redirect('/customers')

  resources :customers
  resources :payment_methods, only: [:index, :show, :new, :create, :destroy]
  resources :payments, only: [:index, :show, :new, :create, :destroy] do
    member do
      post :pay
      post :confirm
    end
  end
  resources :payment_transactions, only: [:index, :show]
end

app/models/payment.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: payments
#
#  id                  :integer          not null, primary key
#  customer_id         :integer          not null
#  revolut_order_id    :string           not null
#  amount              :decimal(19, 2)   not null
#  status_id           :integer(2)       not null
#  force_three_ds      :boolean          default(FALSE), not null
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  last_transaction_id :integer
#
# Indexes
#
#  index_payments_on_customer_id          (customer_id)
#  index_payments_on_last_transaction_id  (last_transaction_id)
#
# Foreign Keys
#
#  customer_id          (customer_id => customers.id)
#  last_transaction_id  (last_transaction_id => payment_transactions.id)
#
class Payment < ApplicationRecord
  STATUS_ID_PENDING = 1
  STATUS_ID_WAIT_THREE_DS = 2
  STATUS_ID_COMPLETED = 3
  STATUS_ID_CANCELED = 4
  STATUS_IDS = {
    STATUS_ID_PENDING => 'Pending',
    STATUS_ID_WAIT_THREE_DS => 'Wait 3DS',
    STATUS_ID_COMPLETED => 'Completed',
    STATUS_ID_CANCELED => 'Canceled'
  }.freeze

  belongs_to :customer, class_name: 'Customer'
  has_many :transactions, class_name: 'PaymentTransaction', dependent: :restrict_with_exception
  belongs_to :last_transaction, class_name: 'PaymentTransaction', optional: true

  attr_readonly :customer_id

  before_validation(on: :create) { self.status_id = STATUS_ID_PENDING }
  validates :amount, numericality: { greater_than_or_equal_to: 0.01 }
  validates :status_id, inclusion: { in: STATUS_IDS.keys }

  before_create { self.revolut_order_id = create_revolut_order[:id] }

  def display_name
    "#{id} | $#{amount} (#{status})"
  end

  def status
    STATUS_IDS[status_id]
  end

  def pending?
    status_id == STATUS_ID_PENDING
  end

  def wait_three_ds?
    status_id == STATUS_ID_WAIT_THREE_DS
  end

  def canceled?
    status_id == STATUS_ID_CANCELED
  end

  def completed?
    status_id == STATUS_ID_COMPLETED
  end

  # https://developer.revolut.com/docs/accept-payments/tutorials/save-and-charge-payment-methods/checkout-with-saved-card/
  # https://developer.revolut.com/docs/accept-payments/3d-secure-overview/
  def pay(payment_method_id:)
    payment_method = customer.payment_methods.find(payment_method_id)
    # error if status_id != pending

    order_data = revolut_order
    case order_data[:state]
    when RevolutMerchant::CONST::ORDER_STATE_PENDING
      # transaction should be created
      last_transaction = PaymentTransaction.create!(payment: self, payment_method:, customer:)
      update!(last_transaction:)
    when RevolutMerchant::CONST::ORDER_STATE_AUTHORISED
      errors.add(:base, 'payment already paid')
      true
    when RevolutMerchant::CONST::ORDER_STATE_COMPLETED
      errors.add(:base, 'payment already completed')
      false
    else
      raise ArgumentError, "invalid revolut order #{order_data[:id]} state #{order_data[:state]}"
    end
  end

  def confirm
    if completed?
      errors.add(:base, 'payment already completed')
      return false
    end

    if revolut_order[:state] != RevolutMerchant::CONST::ORDER_STATE_COMPLETED
      RevolutMerchant::Client.order_capture(revolut_order_id)
    end
    update(status_id: STATUS_ID_COMPLETED)
  end

  def revolut_order
    RevolutMerchant::Client.order(revolut_order_id)
  end

  private

  def create_revolut_order
    amount_cents = (amount * 100).to_i
    enforce_challenge = if force_three_ds
                          RevolutMerchant::CONST::ENFORCE_CHALLENGE_FORCED
                        else
                          RevolutMerchant::CONST::ENFORCE_CHALLENGE_AUTOMATIC
                        end
    RevolutMerchant::Client.order_create(
      customer_id: customer.revolut_customer_id,
      amount: amount_cents,
      currency: RevolutMerchant::CONST::CURRENCY_USD,
      capture_mode: RevolutMerchant::CONST::CAPTURE_MODE_MANUAL,
      enforce_challenge:
    )
  end
end

app/controllers/payments_controller.rb
# frozen_string_literal: true

class PaymentsController < ApplicationController
  before_action :build_payment, only: [:new, :create]
  before_action :find_payment, only: [:show, :pay, :confirm, :destroy]

  def index
    scope = Payment.preload(:customer)
    customer_id = params.dig(:q, :customer_id)
    scope = scope.where(customer_id:) if customer_id.present?
    @payments = scope.to_a
  end

  def show
    @revolut_order_state = @payment.revolut_order[:state]
  end

  def new
    customer = Customer.find params[:customer_id]
    @payment.assign_attributes(customer:)
  end

  def create
    permitted_params = params.require(:payment).permit(:amount, :customer_id, :force_three_ds)
    @payment.assign_attributes(permitted_params)
    if @payment.save
      flash[:notice] = 'Payment created'
      redirect_to payment_path(@payment.id)
    else
      render :new, status: 422
    end
  end

  def pay
    permitted_params = params.require(:payment_transaction).permit(:payment_method_id).to_h.symbolize_keys
    if @payment.pay(**permitted_params)
      flash[:notice] = 'Payment processing started'
    else
      flash[:alert] = "Can't remove payment: #{@payment.errors.full_messages.to_sentence}"
    end
    redirect_to payment_path(@payment.id)
  end

  def confirm
    if @payment.confirm
      flash[:notice] = 'Payment processing started'
    else
      flash[:alert] = "Can't remove payment: #{@payment.errors.full_messages.to_sentence}"
    end
    redirect_to payment_path(@payment.id)
  end

  def destroy
    if @payment.destroy
      flash[:notice] = 'Payment destroyed'
      redirect_to payments_path
    else
      flash[:alert] = "Can't remove payment: #{@payment.errors.full_messages.to_sentence}"
      redirect_back fallback_location: payment_path(@payment.id)
    end
  end

  private

  def build_payment
    @payment = Payment.new
  end

  def find_payment
    @payment = Payment.find params[:id]
  end

  def current_menu
    :payments
  end
end

app/views/payments/index.html.erb
<div class="flex justify-between">
  <div class="page-heading">Payment methods</div>
</div>

<div class="flex flex-col gap-y-4">
  <%= form_for :q, url: current_path, method: :get do |f| %>
    <div class="card relative flex flex-row gap-x-2 items-center p-4 w-fit">
      <%= f.label :customer_id, 'Customer ID' %>
      <%= f.text_field :customer_id, value: params.dig(:q, :customer_id) %>
      <%= f.submit 'Filter', class: 'btn-primary' %>
      <%= link_to 'Clear', current_path, class: 'link-primary' %>
    </div>
  <% end %>


  <% if @payments.any? %>
    <div class="card relative overflow-x-auto">
      <table class="text-sm text-left text-gray-500 w-full">
        <thead class="text-xs text-gray-700 font-semibold bg-gray-200">
        <tr>
          <th scope="col" class="px-6 py-3 w-0">ID</th>
          <th scope="col" class="px-6 py-3 w-0">
            <span class="sr-only">Actions</span>
          </th>
          <th scope="col" class="px-6 py-3">Customer</th>
          <th scope="col" class="px-6 py-3">Status</th>
          <th scope="col" class="px-6 py-3">Amount</th>
          <th scope="col" class="px-6 py-3">Force&nbsp;3DS</th>
          <th scope="col" class="px-6 py-3">Created&nbsp;At</th>
          <th scope="col" class="px-6 py-3">Updated&nbsp;At</th>
          <th scope="col" class="px-6 py-3">Revolut&nbsp;ID</th>
        </tr>
        </thead>
        <tbody>
        <% @payments.each do |payment| %>
          <tr class="bg-white odd:bg-gray-50 border-b hover:bg-gray-100">
            <td class="px-6 py-4"><%= payment.id %></td>
            <td class="px-6 py-4">
              <div class="flex flex-row justify-end gap-x-2">
                <%= link_to 'Show', payment_path(payment.id), class: 'link-primary' %>
              </div>
            </td>
            <td class="px-6 py-4">
              <%= link_to payment.customer.display_name,
                          customer_path(payment.customer_id),
                          class: 'link-primary' %>
            </td>
            <td class="px-6 py-4"><%= payment.status %></td>
            <td class="px-6 py-4"><%= payment.amount %></td>
            <td class="px-6 py-4"><%= payment.force_three_ds ? 'Yes' : 'No' %></td>
            <td class="px-6 py-4"><%= payment.created_at %></td>
            <td class="px-6 py-4"><%= payment.updated_at %></td>
            <td class="px-6 py-4 whitespace-nowrap"><%= payment.revolut_order_id %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  <% else %>
    <div class="p-5">nothing</div>
  <% end %>
</div>

app/views/payments/new.html.erb
<div class="pb-4">
  <%= link_to '<- Back', payments_path, class: 'link-primary' %>
</div>

<div class="flex justify-between pb-2">
  <div class="page-heading">New Payment</div>
</div>

<div class="flex flex-row gap-x-4">
  <%= form_for @payment do |f| %>
    <div class="card p-4 flex flex-col gap-y-6 w-fit">
      <%= semantic_errors(f) %>
      <%= f.hidden_field(:customer_id, value: @payment.customer_id) %>

      <div>
        <%= f.label :amount, class: 'block' %>
        <%= f.number_field :amount, step: '0.01', class: 'form-input' %>
        <%= form_error(f, :amount) %>
      </div>

      <div>
        <%= f.label :force_three_ds, 'Force 3DS', class: 'block' %>
        <%= f.select :force_three_ds,
                     [['Yes', true], ['No', false]],
                     {},
                     class: 'form-select w-full' %>
        <%= form_error(f, :force_three_ds) %>
      </div>

      <%= f.submit 'Submit', class: 'btn-primary w-full' %>
    </div>
  <% end %>

  <%= render 'customers/customer', customer: @payment.customer %>
</div>

app/views/payments/show.html.erb
<div class="pb-4">
  <%= link_to '<- Back', payments_path, class: 'link-primary' %>
</div>

<div class="flex justify-between pb-2">
  <div class="page-heading">Payment №<%= @payment.id %></div>

  <div class="flex items-center gap-x-2">
    <% if @payment.pending? && @revolut_order_state == RevolutMerchant::CONST::ORDER_STATE_PENDING %>
      <%= form_for PaymentTransaction.new, url: pay_payment_path(@payment.id) do |f| %>
        <div class="card w-fit h-fit flex flex-row gap-x-4 px-4 py-2 items-center">
          <div class="flex flex-row gap-x-2 items-center">
            <%= f.label :payment_method_id %>
            <%= f.select :payment_method_id,
                         options_from_collection_for_select(@payment.customer.payment_methods.to_a, :id, :display_name),
                         { include_blank: true },
                         class: 'form-select' %>
          </div>
          <%= f.submit 'Pay', class: 'btn-primary' %>
        </div>
      <% end %>
    <% end %>

    <% if @payment.pending? && @revolut_order_state == RevolutMerchant::CONST::ORDER_STATE_AUTHORISED %>
      <%= button_to 'Confirm',
                    confirm_payment_path(@payment.id),
                    method: :post,
                    class: 'btn-primary' %>
    <% end %>

    <% if @payment.wait_three_ds? %>
      <%= link_to 'Confirm 3DS', '#', class: 'btn-primary' %>
    <% end %>

    <% if @payment.pending? || @payment.wait_three_ds? %>
      <%= button_to "Remove",
                    payment_path(@payment.id),
                    class: 'btn-danger',
                    method: :delete,
                    form: {
                      data: { turbo_confirm: "Are you sure?" }
                    } %>
    <% end %>
  </div>
</div>

<div class="flex flex-row gap-x-4 mb-4">
  <div class="card relative w-min h-fit p-2">
    <div class="p-2 font-semibold">Payment details</div>
    <table class="text-sm text-left text-gray-500">
      <tbody>
      <tr class="bg-white border-b">
        <th scope="col" class="text-xs text-gray-700 uppercase px-6 py-3 border-r">ID</th>
        <td class="px-6 py-4"><%= @payment.id %></td>
      </tr>
      <tr class="bg-white border-b">
        <th scope="col" class="text-xs text-gray-700 uppercase px-6 py-3 border-r">Customer</th>
        <td class="px-6 py-4">
          <%= link_to @payment.customer.display_name,
                      customer_path(@payment.customer_id),
                      class: 'link-primary' %>
        </td>
      </tr>
      <tr class="bg-white border-b">
        <th scope="col" class="text-xs text-gray-700 uppercase px-6 py-3 border-r">Last&nbsp;Transaction&nbsp;ID</th>
        <td class="px-6 py-4"><%= @payment.last_transaction_id %></td>
      </tr>
      <tr class="bg-white border-b">
        <th scope="col" class="text-xs text-gray-700 uppercase px-6 py-3 border-r">Status</th>
        <td class="px-6 py-4"><%= @payment.status %></td>
      </tr>
      <tr class="bg-white border-b">
        <th scope="col" class="text-xs text-gray-700 uppercase px-6 py-3 border-r">Amount</th>
        <td class="px-6 py-4"><%= @payment.amount %></td>
      </tr>
      <tr class="bg-white border-b">
        <th scope="col" class="text-xs text-gray-700 uppercase px-6 py-3 border-r">Force 3DS</th>
        <td class="px-6 py-4"><%= @payment.force_three_ds ? 'Yes' : 'No' %></td>
      </tr>
      <tr class="bg-white border-b">
        <th scope="col" class="text-xs text-gray-700 uppercase px-6 py-3 border-r">Created&nbsp;At</th>
        <td class="px-6 py-4 whitespace-nowrap"><%= @payment.created_at %></td>
      </tr>
      <tr class="bg-white border-b">
        <th scope="col" class="text-xs text-gray-700 uppercase px-6 py-3 border-r">Updated&nbsp;At</th>
        <td class="px-6 py-4 whitespace-nowrap"><%= @payment.updated_at %></td>
      </tr>
      <tr class="bg-white">
        <th scope="col" class="text-xs text-gray-700 uppercase px-6 py-3 border-r">Revolut&nbsp;ID</th>
        <td class="px-6 py-4 whitespace-nowrap"><%= @payment.revolut_order_id %></td>
      </tr>
      </tbody>
    </table>
  </div>

  <div class="card relative w-min p-4 overflow-x-auto">
    <div class="mb-4 font-semibold">Revolut Order</div>
    <pre><%= JSON.pretty_generate @payment.revolut_order %></pre>
    <% if @payment.last_transaction_id %>
      <div class="mt-4 mb-4 font-semibold">Last Revolut Payment</div>
      <pre><%= JSON.pretty_generate @payment.last_transaction.revolut_payment %></pre>
    <% end %>
  </div>
</div>

<% if @payment.transactions.any? %>
  <div class="card relative overflow-x-auto">
    <table class="text-sm text-left text-gray-500 w-full">
      <thead class="text-xs text-gray-700 font-semibold bg-gray-200">
      <tr>
        <th scope="col" class="px-6 py-3 w-0">ID</th>
        <th scope="col" class="px-6 py-3 w-0">
          <span class="sr-only">Actions</span>
        </th>
        <th scope="col" class="px-6 py-3">Payment Method</th>
        <th scope="col" class="px-6 py-3">Created&nbsp;At</th>
        <th scope="col" class="px-6 py-3">Updated&nbsp;At</th>
        <th scope="col" class="px-6 py-3">Revolut&nbsp;ID</th>
      </tr>
      </thead>
      <tbody>
      <% @payment.transactions.order(id: :desc).each do |payment_transaction| %>
        <tr class="bg-white odd:bg-gray-50 border-b hover:bg-gray-100">
          <td class="px-6 py-4"><%= payment_transaction.id %></td>
          <td class="px-6 py-4">
            <div class="flex flex-row gap-x-2">
              <%= link_to 'Show',
                          payment_transaction_path(payment_transaction.id),
                          class: 'link-primary' %>
            </div>
          </td>
          <td class="px-6 py-4">
            <div class="flex flex-row gap-x-2">
              <%= link_to payment_transaction.payment_method.display_name,
                          payment_method_path(payment_transaction.payment_method_id),
                          class: 'link-primary' %>
            </div>
          </td>
          <td class="px-6 py-4"><%= payment_transaction.created_at %></td>
          <td class="px-6 py-4"><%= payment_transaction.updated_at %></td>
          <td class="px-6 py-4 whitespace-nowrap"><%= payment_transaction.revolut_payment_id %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
<% end %>